### ISSUE TITLE
プロジェクト管理: ドキュメント整備とCI/CD設定

### ISSUE THREAD

**Issue by junichiro** [junichiro/tobelog#18]
## 概要
プロジェクトの保守性向上とチーム開発効率化のためのドキュメント整備とCI/CD設定を実装する

### ドキュメント作成
- [ ] README.md の作成
- [ ] API仕様書の作成
- [ ] インストール・セットアップガイド
- [ ] 運用マニュアル作成

### README.md 構成
```markdown
# tobelog - 個人ブログシステム

## 概要
Dropboxをメインストレージとして活用するRust製の個人ブログシステム

## 特徴
- Dropboxストレージ連携
- Markdown記事管理
- LLM生成記事対応
- レスポンシブデザイン

## セットアップ
...

## 使用方法
...

## API仕様
...
```

### CI/CD設定
- [ ] GitHub Actions ワークフロー作成
- [ ] 自動テスト実行
- [ ] コードフォーマット検証
- [ ] セキュリティスキャン
- [ ] Docker イメージビルド

### GitHub Actions ワークフロー例
```yaml
name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Run tests
      run: cargo test
    - name: Run clippy
      run: cargo clippy -- -D warnings
    - name: Run fmt
      run: cargo fmt --check
```

### コード品質管理
- [ ] .gitignore の整備
- [ ] .editorconfig 設定
- [ ] rustfmt.toml 設定
- [ ] clippy.toml 設定

### セキュリティ設定
- [ ] 依存関係の脆弱性スキャン
- [ ] シークレット検出設定
- [ ] セキュリティポリシー文書
- [ ] 脆弱性対応手順

### 開発環境設定
- [ ] 開発用Docker Compose
- [ ] VS Code devcontainer 設定
- [ ] デバッグ設定
- [ ] 開発用環境変数テンプレート

## API仕様書構成
- [ ] OpenAPI/Swagger 仕様書
- [ ] エンドポイント一覧
- [ ] リクエスト/レスポンス例
- [ ] エラーコード定義

## 運用ドキュメント
- [ ] システム監視手順
- [ ] バックアップ・復旧手順
- [ ] トラブルシューティングガイド
- [ ] パフォーマンスチューニングガイド

## 受入条件
- README.mdが完整している
- CI/CDパイプラインが動作する
- API仕様書が正確である
- 開発環境が簡単にセットアップできる

## 継続的改善
- [ ] 定期的な依存関係更新
- [ ] パフォーマンス監視
- [ ] ユーザーフィードバック収集
- [ ] 機能改善計画
